[versions]
geomatys-backend = "2024.5"

[libraries]
geomatys-backend-bom = { module = "com.geomatys.backend:downstream-bom", version.ref = "geomatys-backend" }

[plugins]
geomatys-boot-convention = { id = "com.geomatys.spring-boot-convention", version.ref = "geomatys-backend" }
